### ISSUE TITLE
Appliance ON / OFF

### ISSUE THREAD

**Issue by marciahon29** [voelkerb/FIRED_dataset_helper#10]
Hello,

I am inquiring about : Fridge / Television / Office PC.

I merged these together and did k-means clustering (80% Train and 20% Test) for 8 clusters.

The clusters (8) being: Fridge / Television / OfficePC / Fridge + Television / Fridge + OfficePC / OfficePC + Television/ Fridge + Television + OfficePC / Nothing.

The issue is that all three appliances are always turned on (there is always "active_power"). Is there some sort of threshold for each appliance? How could I find these thresholds?

Thanks,
Marcia

**Comment by voelkerb** [comment]
I am not really sure what you mean. The devices draw variable power depending on their current state (e.g. the television depending on the content of the TV and brightness setting etc., the office PC depending on what is computed...) K-means will not be able to detect these appliances based on active power alone. Furthermore, whenever you use aggregated data you would need to use the delta power but I guess you are aware of that.
