### ISSUE TITLE
Smart Meter + Appliance

### ISSUE THREAD

**Issue by marciahon29** [voelkerb/FIRED_dataset_helper#12]
Hello,

I am trying to get the Voltage/Current for the devices (fridge, office_pc, television).

For, fridge, my understanding is that I do something like this: fridge = hp.getMeterVI("powermeter09", start...)

So the fridge is found at the meter called "powermeter09".

Please could you let me know what meter names are associated with office_pc and television?

Thanks

**Comment by voelkerb** [comment]
Take a look at the helper.py with its functions.

**Comment by marciahon29** [comment]
I try this: vi_data = hp.getMeterVI("powermeter20", startTs=startTs, stopTs=stopTs)
and get this error: error retreiving file: -1

Would you have any idea what I am missing?

**Comment by voelkerb** [comment]
You can enable verbose logging in the helper file and try to find out what is going on. I suspect that the corresponding high frequency file is missing and cannot be loaded using rsync

**Comment by marciahon29** [comment]
ok, I think you are right...

My verbose error:
C:\Users\marci\COCA - Paper02\FIRED\highFreq\powermeter20\powermeter20_2020_06_14__00_10_00.mkv
File: C:\Users\marci\COCA - Paper02\FIRED\highFreq\powermeter20\powermeter20_2020_06_14__00_10_00.mkv does not exist, using rsync to download
rsync --password-file=C:\Users\marci\COCA - Paper02\FIRED\info\rsync_pass.txt rsync://FIRED@clu.informatik.uni-freiburg.de/FIRED//highFreq/powermeter20/powermeter20_2020_06_14__00_10_00.mkv C:\Users\marci\COCA - Paper02\FIRED\highFreq\powermeter20
error retreiving file: -1

I *believe* I have to change this (from helper.py): RSYNC_ADDR = "rsync://FIRED@clu.informatik.uni-freiburg.de/FIRED/"
Another possiblity is (there are single "/" and double "//"): rsync://FIRED@clu.informatik.uni-freiburg.de/FIRED//highFreq/powermeter20/powermeter20_2020_06_14__00_10_00.mkv

I look forward to your feedback.

Thanks,
Marcia

**Comment by marciahon29** [comment]
i *believed* my problem was that I did not have the "rsync_pass.txt" file. So I created one with the content of "nobodyGetsFIRED". Unfortunately, the same error persists. 

I also tried to download my files: highFreq/powermeter09 , highFreq/powermeter20 , highFreq/powermeter23. But I had to give up because it takes over a lot of space which I do not have.

Please could you give me any suggestions to improve upon this error?

Thanks

**Comment by marciahon29** [comment]
I have also tried the following:

import helper as hp
hp.FIRED_BASE_FOLDER = "C:\\Users\\marci\\COCA - Paper02\\FIRED"
startTs,  stopTs = hp.getRecordingRange("2020.06.14 00:00:00", "2020.09.21 16:59:59")
hp.getMeterFiles("powermeter23", 1, startTs=startTs, stopTs=stopTs)

hp.RSYNC_ALLOWED = False

vi_data = hp.getMeterVI("powermeter23", 1, startTs=startTs, stopTs=stopTs)

voltage = vi_data["data"]["v"]
current = vi_data["data"]["i"]

print(voltage.head())
print(current.head())

But it seems that I am not able to download all the files.

**Comment by voelkerb** [comment]
You are trying to load over 3 months of high frequency data. This will always be very space demanding. The complete dataset is over 3TB. I suggest loading the data day by day, do the calculation you need and throw away the raw data afterwards

**Comment by voelkerb** [comment]
I am not able to test it on a windows machine as you have, but this probably might be a problem too. You can maybe manually download one meter a time, so the calculations and trash the data.

**Comment by voelkerb** [comment]
Have you tried other timestamps?

**Comment by marciahon29** [comment]
sorry, I don't understand the context of your question.

**Comment by marciahon29** [comment]
Hello,

I keep getting this message:
SystemExit: File Y:\PhD_Progress\2024 - 2025\02 - NILM Anomaly Detection with Self-Supervised Learning\FIRED_Dataset_powermeter_09_20_23\highFreq\powermeter09\powermeter09_2020_06_14__02_10_00.mkv does not exist

It appears that you are missing the file: powermeter09_2020_06_14__02_10_00.mkv

I was able to download everything from the server and get this message.

**Comment by voelkerb** [comment]
Hm possible that the file is missing/got lost but this is very uncertain. Does it exist in your file browser? Furthermore, the path seems a little odd. Have you set the fired base folder differently? Highfreq should be in the fired base folder. Is this happening with other files (timestamps) or just with this single file? I may be able to test it tomorrow and reach back to you but in the meantime, try if the issue is similar if you try to load high frequency data from another time window

**Comment by voelkerb** [comment]
If the file exists, though, it might be spaces and special characters in the path.

**Comment by voelkerb** [comment]
were you able to resolve it? can the issue be closed?

**Comment by marciahon29** [comment]
yes. thank you
