### ISSUE TITLE
Temperature + Humidity

### ISSUE THREAD

**Issue by marciahon29** [voelkerb/FIRED_dataset_helper#13]
Hello,

I was searching through the literature and I do not know how to extract : temperature and humidity.

I read your paper, and you mention that you record these parameters. But I cannot seem to find out how it's done.

Thanks

**Comment by voelkerb** [comment]
See the [loadAnnotation()](https://github.com/voelkerb/FIRED_dataset_helper/blob/master/helper.py#L414) function.
