### ISSUE TITLE
Television

### ISSUE THREAD

**Issue by marciahon29** [voelkerb/FIRED_dataset_helper#14]
Hello,

I am investigating your television data. 

It appears that there is a significant amount of time when the television is not being used.

Is this a mistake? How could you explain this?

Thanks

**Comment by voelkerb** [comment]
The sensor used to capture this was an infrared receiver. So either the tv has been turned on using its dedicated switch on button, the receiver didn't capture the signals or the television was really not used which you can simply cross check with the power meter data.
