### ISSUE TITLE
Lighting Information

### ISSUE THREAD

**Issue by marciahon29** [voelkerb/FIRED_dataset_helper#15]
Hello,

I understand that you have lighting information with regards to: ON/OFF, Dimm, and Colour.

I would like to ask you if these are based on what room? For example, my idea is, if a room has lights on, most likely someone is in that room.

Additionally, are Temperature/Humidity based on the local weather in Freiberg (Germany), or are they measurements from inside the residence?

Thanks,
Marcia

**Comment by voelkerb** [comment]
The room name of the light and of the individual sensor is prefixed with the name. Humidity and temperature are indoor (hence the prefixed room name)

Example:
`light__bedroom__bedroom_ceiling_light_#1__GU10_400lm.csv`

`sensor__livingroom__temp.csv`
