### ISSUE TITLE
Power Data - Negatives and Zeros

### ISSUE THREAD

**Issue by marciahon29** [voelkerb/FIRED_dataset_helper#6]
Hello,

I have checked for one appliance.

Please could you explain why and how to resolve where the power is negative? How could this happen? Are these negative points incorrect and should be replaced with zero?

Also, towards the end of the metering range, there are lots of consecutive points that have zero for powers. Please could you let me know if this is wrong and how to correct is?

Thanks,
Marcia

**Comment by marciahon29** [comment]
In the fridge data, there are lots of instantaneous spikes. Please could
you guide me on how to remove these spikes?

**Comment by marciahon29** [comment]
I think I figured this out. There is a filter called "winsorize filter"
which seems to work well with fridge data. So I will proceed with this.

**Comment by voelkerb** [comment]
The fridge broke in the measurement period. Causing instantaneous spikes. Later on the fridge was replaced.
