### ISSUE TITLE
Number of Features

### ISSUE THREAD

**Issue by marciahon29** [voelkerb/FIRED_dataset_helper#7]
Hello,

I am trying to implement NILM using FIRED. The NILM is based on an autoencoder.

My question is, should I use two features (Active/Reactive Power)? or just one feature (Active)?

If I have Active, could I still cluster and be able to distinguish appliance signatures? or must this be done with both Active and Reactive Power.

Thanks,
Marcia

**Comment by voelkerb** [comment]
Hey Marcia,

First of all:
I think you are asking this at the wrong place on the internet ;) I guess that is a question for a machine learning forum or NILM forum. This is just a Repo to give you some dataset to work on. 
Still my feeling ist that active power alone will not be enough to distinguish appliances with roughly the same active consumption. Using LSTM or similar might help but again I am not an expert on this. However I have done some fairly simple analysis on how the use different features and combinations affect the performance of classical machine learning methods. See the following paper 
[sesc21](https://link.springer.com/chapter/10.1007/978-3-030-97027-7_7)
