### ISSUE TITLE
Location + Weather Information

### ISSUE THREAD

**Issue by marciahon29** [voelkerb/FIRED_dataset_helper#8]
Hello,

Please could you provide Location and Weather information for the FIRED Dataset?

If you don't have the Weather information, I could probably find it somewhere else given your Location information.

Thanks,
Marcia

**Comment by voelkerb** [comment]
Location is Freiburg Germany

**Comment by marciahon29** [comment]
Thank you.

Please could you also provide the date range for the data? What year/month/day start and finish?

**Comment by voelkerb** [comment]
This information is contained as the timestamp within the data.
