### ISSUE TITLE
Voltage and Current

### ISSUE THREAD

**Issue by marciahon29** [voelkerb/FIRED_dataset_helper#9]
Hello,

Please could you proivde sample code of how to extract the "voltage" and "current"?

I understand that you have "p"/"q"/"s" (Active/Reactive/Apparent Powers). Do you also have "voltage" and "current"?

If not, do you have a manner as to how to calculate voltage/current?

Thanks,
Marcia

**Comment by voelkerb** [comment]
You need to load the high frequency voltage and current data like done [here](https://github.com/voelkerb/FIRED_dataset_helper/blob/master/example.py#L58), chunk it to the individual sine waves (20ms) and calculate the RMS, I advise to first make them mean free. As example see [here](https://github.com/voelkerb/Appliance_Classification_Features/blob/main/features/features.py#L105).

**Comment by voelkerb** [comment]
In case you want RMS, if you want raw waveforms, just use the the current and voltage measurements provided.
